services:
  brawl-stars-api:
    image: openjdk:21
    volumes:
      - /tmp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: brawl-stars-api